services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=easypassword
      - POSTGRES_USER=easyuser
      - POSTGRES_DB=treetracker-like
