apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection
  namespace: treetracker-like-api
spec:
  encryptedData:
    db: AgBMlhGxjXqr61361NKqhGDY2WzZ2dH3gmsyqduoslcQ7SbcmlqQ1APusA3sEK+J+pJDeMijoxTHqZpN5jwrlcG/sL+ljORq6u7FblDf7ZUSzSFpGaZijl5I/SvlSgTdEmFqZ2EsVhZnMfKqhL03F+13Pk6K8Fzsw7bjXOnSiC71Snip/BjRU8ep/zl9X4y11+4VQfn897aZhx1W+aTkZBWd6H8Qjv/mTDsTho/X59DkrcP9vTxISjc6B44qmKz6l6n42ER7vrcalV9Vd9DCwL2t5vpfOAy3taBBg02Cw+GQOq3ZtcQg7CrjYhPGSFvTaS7bz4Tt8Hbox+vfzAKJ2OUNO/NKwqnWjhY7W3tO1P1ZArb6yjj/SeHepiXgDWuwjkwWH+qNK4h8KbaxJ70fqneT0mksGZruSj95Mi4W4nD0LFAa+OAe3D04iYmhMvvFKz/7/psO1S1+RbTirIEX6U7I8rDEc7jVfEIh4wDAd1vgScfcJa/UAC/ZLzW0tr8jiEyv8YbRp36fF2LxiE9C8yo72z4Y9lR1uGwXVbz1p9VmDtmJuG1UVRHj9US5RCfAPGSPLJxn45pIUqkVbgqAHwHBpTTbYK4zppnkaIbzcgV4qsIob+WGElHrz0ynDzvYaRgFzC3lvOK1+b+YfJ3u5O9ZP0OeFTCu9P9FjCto/EyeOYhBB24Y/gywbnaqSqxg7PJmVXgIrlSEnphZGF5h4mQpL6yrxcE2NW7qJS5ohlEoTIZ7T0/geZC3Bnqi3vZsUOY1pzuEa6b66ZKxqsE/Uan42rgGqT8tph7ZTSK13aZWztInv7dKnCXbPF/YJnlCp1jT6vDc7TpwXZbKcq16QbPIXEBLqtJe3AB9iEQ5FU5hR/BZWQc6fyTYXYjZ6R7qQp99
  template:
    metadata:
      name: database-connection
      namespace: treetracker-like-api

