apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection
  namespace: treetracker-like-api
spec:
  encryption:
    db: PLACEHOLDER
  template:
    metadata:
      name: database-connection
      namespace: treetracker-like-api