apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-like-api
  labels:
    app: treetracker-like-api
  namespace: treetracker-like-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-like-api
  template:
    metadata:
      labels:
        app: treetracker-like-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-like-api
          image: treetracker-like
          ports:
            - containerPort: 3006
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
