resources:
  - deployment.yaml
  - mapping.yaml
  - service.yaml
  - db-connection-sealed-secret.yaml
  - namespace.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - database-migration-job.yaml
