apiVersion: v1
kind: Service
metadata:
  name: treetracker-like-api-service
  namespace: treetracker-like-api
spec:
  selector:
    app: treetracker-like-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
  type: ClusterIP
