openapi: 3.0.0
info:
  title: Treetracker Wallet API
  contact: {}
  version: '1.28.0'
servers:
  - url: https://localhost:3010
    variables:
      environment:
        default: dev
        enum:
          - dev     # Development server
          - test    # Test server
paths:
  '/types/{type_uuid}/things/{object_uuid}':
    post:
      tags:
        - Like / unlike a likable object and get the like counts
      summary: Get the like count of a likable object
      description: 'Get the like count of a likable object'
      parameters:
        - name: type_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-446655440000'
        - name: object_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-196655440000'
      requestBody:
        description: 'User OIDC access token'
        content:
          application/json: 
            example: 
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '200':
          description: 'Successfully retrieve the object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/likableObject'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/MissingParameterError'
      deprecated: false
  '/types/{type_uuid}/things/{object_uuid}/like':
    post:
      tags:
        - Like / unlike a likable object and get the like counts
      summary: Like a likable object
      description: 'Like a likable object'
      parameters:
        - name: type_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-446655440000'
        - name: object_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-196655440000'
      requestBody:
        description: 'User OIDC access token'
        content:
          application/json: 
            example: 
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '201':
          description: 'Successfully like the object response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/likableObject'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/MissingParameterError'
      deprecated: false
  '/types/{type_uuid}/things/{object_uuid}/unlike':
    post:
      tags:
        - Like / unlike a likable object and get the like counts
      summary: Unlike a likable object
      description: 'Unlike a likable object'
      parameters:
        - name: type_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-446655440000'
        - name: object_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-196655440000'
      requestBody:
        description: 'User OIDC access token'
        content:
          application/json: 
            example: 
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '201':
          description: 'Successfully unlike the object response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/likableObject'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/MissingParameterError'
      deprecated: false
  '/types':
    get:
      tags:
        - Types info and manipulation
      summary: Get types name and id
      description: 'Get types name and id'
      responses:
        '200':
          description: 'Successfully retrieve types info'
          content:
            application/json:
              example:
                550e8400-e29b-41d4-a716-446655440010: countries
                550e8400-e29b-41d4-a716-446655440001: organizations
                550e8400-e29b-41d4-a716-446655440019: planters
                550e8400-e29b-41d4-a716-446655440029: species
                550e8400-e29b-41d4-a716-446655440024: trees
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
    post:
      tags:
        - Types info and manipulation
      summary: Create a new type in the database
      description: 'Create a new type in the database'
      requestBody:
        description: 'Name of new type'
        content:
          application/json: 
            example: 
              name: 'trees'
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '201':
          description: 'Successfully create new type'
          content:
            application/json:
              example:
                550e8400-e29b-41d4-a716-446655440019: 'trees'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
  '/types/{type_uuid}':
    patch:
      tags:
        - Types info and manipulation
      summary: Create a new type in the database
      description: 'Create a new type in the database'
      parameters:
        - name: type_uuid
          description: 'ID of specific token to retrieve'
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: '550e8400-e29b-41d4-a716-446655440000'
      requestBody:
        description: 'Name of new type'
        content:
          application/json: 
            example:
              name: 'above_the_ground_trees'
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '200':
          description: 'Successfully modified the type'
          content:
            application/json:
              example:
                5: 'above_the_ground_trees'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotfoundError'
      deprecated: false

  '/user/likes':
    post:
      tags:
        - Get user like / unlike activities
      summary: Get user like / unlike activities
      description: 'Get user like / unlike activities'
      requestBody:
        description: 'User OIDC access token'
        content:
          application/json: 
            example: 
              access_token: '{{ACCESS_TOKEN}}'
        required: true
      responses:
        '200':
          description: 'Successfully retrieve user activities'
          content:
            application/json:
              example:
                550e8400-e29b-41d4-a716-446655440001: [550e8400-e29b-41d4-a716-446655440024,550e8400-e29b-41d4-a716-446655440029]
                550e8400-e29b-41d4-a716-446655440010: [550e8400-e29b-41d4-a716-446655440019, 550e8400-e29b-41d4-a716-446655440025]
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotfoundError'
      deprecated: false
  
components:
  responses:
    MissingParameterError:
      description: 'Missing request parameters'
      content:
        application/json:
          example:
            code: 422
            message: 'type_uuid is not allowed to be empty'
    UnauthorizedError:
      description: 'Access is missing or invalid'
      content:
        application/json:
          example:
            code: 401
            message: 'Access is missing or invalid'
    NotfoundError:
      description: 'Not found'
      content:
        application/json:
          example:
            code: 404
            message: 'User not found'
  parameters:
    accessToken:
      name: access_token
      in: header
      description: 'Specifies the user information, mostly the user id'
      required: true
      style: simple
      schema:
        type: string
        example: {{ACCESS_TOKEN}}
  schemas:
    likableObject:
      title: Likeable object
      required:
        - objectType
        - objectId
        - numLikes
      type: object
      properties:
        objectType:
          type: string
          example: trees
        objectId:
          type: string
          example: 186734
        numLikes:
          type: number
          example: 10