
name: CI for New Pull Requests

on:
  push:
    branches:
      - '*'



jobs:

  test:
    name: Run all tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm clean install
        run: npm ci

      - name: Typescript compiles
        run: npx nx build like

      - name: Eslint
        run: npx nx lint like
        continue-on-error: true
      
      - name: database migration
        run: npm run migration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: run tests
        run: npx nx test like

